### ISSUE TITLE
sea-ice : add validity date

### ISSUE THREAD

**Issue by JulesBoulard** [LouisPauchet/UNIS_SvalbardWeatherInformation#7]
Add validity date of the sea ice layer (in the legend?) as updates of this layer are sometimes delayed

**Comment by LouisPauchet** [comment]
The date of publication and of last update is now displayed in the legend area. https://github.com/LouisPauchet/UNIS_SvalbardWeatherInformation/commit/09f6b6bf7eeee4d6afaaa7a557a02a70aedc7d18
